version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_SOURCE: ${DB_SOURCE}
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      PORT: 8080
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_SOURCE: ${DB_SOURCE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
